input {
  beats {
    port => 5044
  }
}

#filter {
 # grok {
  #  match => { "message" => "%{COMBINEDAPACHELOG}" }
 # }
#}

filter {
  grok {
    match => {
      "message" => "%{TIMESTAMP_ISO8601:log_timestamp},%{INT:millis}:%{LOGLEVEL:log_level}:%{IP:client_ip} - - \[%{HTTPDATE:access_time}\] \"%{WORD:http_method} %{URIPATHPARAM:request_path} HTTP/%{NUMBER:http_version}\" %{NUMBER:status_code} -"
    }
    remove_tag => ["_grokparsefailure"]
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
  }
  stdout { codec => rubydebug }
}
